image: docker:19.03.12

services:
  - docker:19.03.12-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - deploy


build:
  stage: build
  script: |
    set -eux
    docker build -t pop .
    docker tag pop "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"

lint:
  image: debian:latest
  stage: test
  script: |
    set -eux
    apt-get update
    apt-get -y upgrade
    apt-get -y dist-upgrade
    apt-get -y install make python3-minimal python3-pip
    pip install -r requirements.txt
    make lint

release:
  stage: deploy
  script: |
    set -eux
    docker pull "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${CI_REGISTRY_IMAGE}:latest"
    docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    docker push "${CI_REGISTRY_IMAGE}:latest"
